sudo: required
language: python
addons:
  apt:
    packages:
    - swig
env:
  global:
    - COVERALLS_PARALLEL=true
cache:
  directories:
    - $HOME/openmc
    - $HOME/miniconda
notifications:
  webhooks: https://coveralls.io/webhook?repo_token=$COVERALLS_REPO_TOKEN
matrix:
  include:
    - python: "3.10"
      env: OMP=n MPI=n
    - python: "3.6"
      env: OMP=n MPI=n
    - python: "3.6"
      env: OMP=y MPI=n
    - python: "3.6"
      env: OMP=y MPI=y
before_install:
  # ========== Point apt-get to C++11-compatible compiler =====================
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
install:
  - chmod +x ./tools/ci/travis-install.sh
  - . ./tools/ci/travis-install.sh
script:
  - cd tests
  - ./travis.sh
after_success:
  - cd ..
  - cpp-coveralls -i src -i build/temp.linux*/src/ --exclude-pattern "/usr/*" --dump cpp_cov.json
  - cp tests/.coverage ./
  - cat .coverage
  # Switch to Python coveralls, which can merge reports
  - coveralls --rcfile=./tests/.coveragerc --merge=cpp_cov.json
