/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import helpers.NeighboursScanner;
import helpers.PropertiesManager;
import java.net.SocketException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import network_layer.TCPClient;

/**
 *
 * @author Breaze
 */
public class Home extends javax.swing.JFrame {
    private TCPClient client;
    
    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        this.loadNeighbours();
        this.client = new TCPClient();
    }

    
    public void loadNeighbours(){
        PropertiesManager pm = new PropertiesManager();
        String neighbour_names[] = pm.getNeighbourNames();
        cmbNuclearPowerPlant.removeAllItems();
        for(String neighbour : neighbour_names)
        {
            cmbNuclearPowerPlant.addItem(neighbour);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cmbNuclearPowerPlant = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmbReactors = new javax.swing.JComboBox<>();
        btnTurnOn = new javax.swing.JButton();
        btnTurnOff = new javax.swing.JButton();
        btnCharge = new javax.swing.JButton();
        btnDischarge = new javax.swing.JButton();
        btnRepair = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtConsole = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnuUpdateList = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(155, 155, 235));

        cmbNuclearPowerPlant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbNuclearPowerPlantActionPerformed(evt);
            }
        });

        jLabel1.setText("Nuclear Power Plant:");

        jLabel2.setText("Reactor: ");

        cmbReactors.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));

        btnTurnOn.setText("Turn On");
        btnTurnOn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTurnOnActionPerformed(evt);
            }
        });

        btnTurnOff.setText("Turn Off");
        btnTurnOff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTurnOffActionPerformed(evt);
            }
        });

        btnCharge.setText("Charge");
        btnCharge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChargeActionPerformed(evt);
            }
        });

        btnDischarge.setText("Discharge");
        btnDischarge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDischargeActionPerformed(evt);
            }
        });

        btnRepair.setText("Repair");
        btnRepair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRepairActionPerformed(evt);
            }
        });

        jLabel3.setText("Console:");

        txtConsole.setEditable(false);
        txtConsole.setColumns(20);
        txtConsole.setRows(5);
        jScrollPane1.setViewportView(txtConsole);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnCharge, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2)
                                    .addComponent(btnTurnOn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(cmbNuclearPowerPlant, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cmbReactors, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnTurnOff, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addComponent(btnDischarge, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGap(18, 18, 18)
                            .addComponent(btnRepair, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel3)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cmbNuclearPowerPlant)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbReactors, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTurnOn)
                    .addComponent(btnTurnOff))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCharge)
                    .addComponent(btnDischarge)
                    .addComponent(btnRepair))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenu1.setText("File");

        mnuUpdateList.setText("Update Nuclear Power Plant List");
        mnuUpdateList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuUpdateListActionPerformed(evt);
            }
        });
        jMenu1.add(mnuUpdateList);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuUpdateListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuUpdateListActionPerformed
        NeighboursScanner ns;
        try {
            ns = new NeighboursScanner();
            ns.searchNuclearPowerPlants();
        } catch (SocketException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.loadNeighbours();
    }//GEN-LAST:event_mnuUpdateListActionPerformed

    private void cmbNuclearPowerPlantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbNuclearPowerPlantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbNuclearPowerPlantActionPerformed

    private void btnTurnOnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTurnOnActionPerformed
        int server = cmbNuclearPowerPlant.getSelectedIndex();
        int reactor = cmbReactors.getSelectedIndex();
        System.out.println(server);
        String info[] = this.getNeighbourInfo(server);
        String ip = info[0];
        int port = Integer.parseInt(info[1]);
        this.client.setServer(ip);
        this.client.setPort(port);
        String msg = "turn_on:"+reactor+":null";
        System.out.println(msg);
        String res = this.client.connect(msg);
        txtConsole.setText(res);
        
    }//GEN-LAST:event_btnTurnOnActionPerformed

    private void btnTurnOffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTurnOffActionPerformed
        int server = cmbNuclearPowerPlant.getSelectedIndex();
        int reactor = cmbReactors.getSelectedIndex();
        String info[] = this.getNeighbourInfo(server);
        String ip = info[0];
        int port = Integer.parseInt(info[1]);
        this.client.setServer(ip);
        this.client.setPort(port);
        String msg = "turn_off:"+reactor+":null";
        System.out.println(msg);
        String res = this.client.connect(msg);
        txtConsole.setText(res);
    }//GEN-LAST:event_btnTurnOffActionPerformed

    private void btnRepairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRepairActionPerformed
        int server = cmbNuclearPowerPlant.getSelectedIndex();
        int reactor = cmbReactors.getSelectedIndex();
        String info[] = this.getNeighbourInfo(server);
        String ip = info[0];
        int port = Integer.parseInt(info[1]);
        this.client.setServer(ip);
        this.client.setPort(port);
        String msg = "repair:"+reactor+":null";
        System.out.println(msg);
        String res = this.client.connect(msg);
        txtConsole.setText(res);
    }//GEN-LAST:event_btnRepairActionPerformed

    private void btnChargeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChargeActionPerformed
        int server = cmbNuclearPowerPlant.getSelectedIndex();
        int reactor = cmbReactors.getSelectedIndex();
        String value = JOptionPane.showInputDialog("Introduce the value to charge");
        String info[] = this.getNeighbourInfo(server);
        String ip = info[0];
        int port = Integer.parseInt(info[1]);
        this.client.setServer(ip);
        this.client.setPort(port);
        String msg = "charge:"+reactor+":"+value;
        System.out.println(msg);
        String res = this.client.connect(msg);
        txtConsole.setText(res);
    }//GEN-LAST:event_btnChargeActionPerformed

    private void btnDischargeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDischargeActionPerformed
        int server = cmbNuclearPowerPlant.getSelectedIndex();
        int reactor = cmbReactors.getSelectedIndex();
        String value = JOptionPane.showInputDialog("Introduce the value to discharge");
        String info[] = this.getNeighbourInfo(server);
        String ip = info[0];
        int port = Integer.parseInt(info[1]);
        this.client.setServer(ip);
        this.client.setPort(port);
        String msg = "discharge:"+reactor+":"+value;
        System.out.println(msg);
        String res = this.client.connect(msg);
        txtConsole.setText(res);
    }//GEN-LAST:event_btnDischargeActionPerformed

    public String[] getNeighbourInfo(int powerPlant){
        String res[] = new String[2];
        PropertiesManager pm = new PropertiesManager();
        String neighbours[] = pm.getNeighbours();
        String ports[] = pm.getNeighbourPorts();
        res[0] = neighbours[powerPlant];
        res[1] = ports[powerPlant];
        return  res;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCharge;
    private javax.swing.JButton btnDischarge;
    private javax.swing.JButton btnRepair;
    private javax.swing.JButton btnTurnOff;
    private javax.swing.JButton btnTurnOn;
    private javax.swing.JComboBox<String> cmbNuclearPowerPlant;
    private javax.swing.JComboBox<String> cmbReactors;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem mnuUpdateList;
    private javax.swing.JTextArea txtConsole;
    // End of variables declaration//GEN-END:variables
}
